a = {
    "title": "LOVE CATCHER",
    "type": "EP",
    "thumbnails": [
        {
            "url": "https://yt3.googleusercontent.com/KkiZjgUI7ADMjnfu90T8szhJ3CqljSdGDIpo3iNmOltOgewijZyI_Z2TQiXDdCN2jlozAVXNjuiyiSsL=w60-h60-l90-rj",
            "width": 60,
            "height": 60,
        },
        {
            "url": "https://yt3.googleusercontent.com/KkiZjgUI7ADMjnfu90T8szhJ3CqljSdGDIpo3iNmOltOgewijZyI_Z2TQiXDdCN2jlozAVXNjuiyiSsL=w120-h120-l90-rj",
            "width": 120,
            "height": 120,
        },
        {
            "url": "https://yt3.googleusercontent.com/KkiZjgUI7ADMjnfu90T8szhJ3CqljSdGDIpo3iNmOltOgewijZyI_Z2TQiXDdCN2jlozAVXNjuiyiSsL=w226-h226-l90-rj",
            "width": 226,
            "height": 226,
        },
        {
            "url": "https://yt3.googleusercontent.com/KkiZjgUI7ADMjnfu90T8szhJ3CqljSdGDIpo3iNmOltOgewijZyI_Z2TQiXDdCN2jlozAVXNjuiyiSsL=w544-h544-l90-rj",
            "width": 544,
            "height": 544,
        },
    ],
    "isExplicit": False,
    "description": None,
    "year": "2026",
    "artists": [{"name": "YENA", "id": "UC4mOLela441MNvGJNy6h8bg"}],
    "trackCount": 5,
    "duration": "15 minutes",
    "audioPlaylistId": "OLAK5uy_ln-901soRWFhLtU8JITVpcy1tk7pHWJbc",
    "likeStatus": "INDIFFERENT",
    "tracks": [
        {
            "videoId": "sjtyqmA-pH4",
            "title": "Catch Catch",
            "artists": [{"name": "YENA", "id": "UC4mOLela441MNvGJNy6h8bg"}],
            "album": "LOVE CATCHER",
            "likeStatus": "INDIFFERENT",
            "inLibrary": False,
            "pinnedToListenAgain": False,
            "feedbackTokens": {
                "add": None,
                "remove": "AB9zfpLfe5vqjHm9CzjzQwMN83KIY4m09WImn1T2thASjAoe8qRD2IMcx1HMaDwjWlhm1Q8sRfTKGQDiQerH1LtC1aaqoXZfIw",
            },
            "thumbnails": None,
            "isAvailable": True,
            "isExplicit": False,
            "videoType": "MUSIC_VIDEO_TYPE_ATV",
            "views": "189K plays",
            "trackNumber": 1,
            "duration": "3:00",
            "duration_seconds": 180,
        },
        {
            "videoId": "_GQ7lx-2MkA",
            "title": "Spring Fever (feat. DINDIN & Jung Hyung Don)",
            "artists": [{"name": "YENA", "id": "UC4mOLela441MNvGJNy6h8bg"}],
            "album": "LOVE CATCHER",
            "likeStatus": "INDIFFERENT",
            "inLibrary": False,
            "pinnedToListenAgain": False,
            "feedbackTokens": {
                "add": None,
                "remove": "AB9zfpIjplXv-PRhdGYjofUfKJ0kx_4g2cuNjMShSdqozeM1rc7UUVXvZsJo4gMvnxyVyJt7GOwPnCpPmatDmKlwDKXi1wsx6g",
            },
            "thumbnails": None,
            "isAvailable": True,
            "isExplicit": False,
            "videoType": "MUSIC_VIDEO_TYPE_ATV",
            "views": "71K plays",
            "trackNumber": 2,
            "duration": "2:38",
            "duration_seconds": 158,
        },
        {
            "videoId": "k94KRRNv0f8",
            "title": "Sticker (feat. MRCH)",
            "artists": [{"name": "YENA", "id": "UC4mOLela441MNvGJNy6h8bg"}],
            "album": "LOVE CATCHER",
            "likeStatus": "INDIFFERENT",
            "inLibrary": False,
            "pinnedToListenAgain": False,
            "feedbackTokens": {
                "add": None,
                "remove": "AB9zfpIMZ2HGPYXcrjVY2uK9zPJIn_6-HJTDMK8wG7kHuU3c1aL53lY2YcDxobpnODDigzII6I1fjT_TtbfQ0ttUBbAx6Sk_kQ",
            },
            "thumbnails": None,
            "isAvailable": True,
            "isExplicit": False,
            "videoType": "MUSIC_VIDEO_TYPE_ATV",
            "views": "64K plays",
            "trackNumber": 3,
            "duration": "3:21",
            "duration_seconds": 201,
        },
        {
            "videoId": "9ikOXwwJB2s",
            "title": "April′s Cat",
            "artists": [{"name": "YENA", "id": "UC4mOLela441MNvGJNy6h8bg"}],
            "album": "LOVE CATCHER",
            "likeStatus": "INDIFFERENT",
            "inLibrary": False,
            "pinnedToListenAgain": False,
            "feedbackTokens": {
                "add": None,
                "remove": "AB9zfpLWWy_KkKU0RHnC-6tHIW0hQ8DT6jQEEPINBpTq-dHvaIpVdfv3SNennS3vlbTfhnkqwUAg885Bhst3XJIqSSdco9T92g",
            },
            "thumbnails": None,
            "isAvailable": True,
            "isExplicit": False,
            "videoType": "MUSIC_VIDEO_TYPE_ATV",
            "views": "49K plays",
            "trackNumber": 4,
            "duration": "3:35",
            "duration_seconds": 215,
        },
        {
            "videoId": "gUb9FNhhhqA",
            "title": "Question Marks (feat. Paul Kim)",
            "artists": [{"name": "YENA", "id": "UC4mOLela441MNvGJNy6h8bg"}],
            "album": "LOVE CATCHER",
            "likeStatus": "INDIFFERENT",
            "inLibrary": False,
            "pinnedToListenAgain": False,
            "feedbackTokens": {
                "add": None,
                "remove": "AB9zfpJRyFDvprEVwW5ZOiBHSqi37ux4UjYNaNXHCUdsvs4xiPU89iMobAsZOg3hFkDsMiunT6tH21mfk-ZY4uCG_NLK8TMSnA",
            },
            "thumbnails": None,
            "isAvailable": True,
            "isExplicit": False,
            "videoType": "MUSIC_VIDEO_TYPE_ATV",
            "views": "37K plays",
            "trackNumber": 5,
            "duration": "2:46",
            "duration_seconds": 166,
        },
    ],
    "duration_seconds": 920,
}
